version: '1.0'
name: pipeline-20250919
displayName: pipeline-20250919
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-0bc90b26
    displayName: Test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: WuLab-Workstation
          hostID:
            - c1e9bc0d-5233-4e2a-8937-df59b5bc29a2
        scriptType: SH
        script:
          - cd /workspace
          - rm -rf /workspace/spikesorting
          - rm -rf /workspace/ITKIT
          - git clone https://gitee.com/MGAM/ITKIT
          - cd ITKIT
          - pip install .[dev,medical_vision]
          - pytest
        notify: []
        strategy:
          retry: '0'
          timeout: 10
